//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UStoreBot.Dialogs.Recipe.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RecipeDialogStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RecipeDialogStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UStoreBot.Dialogs.Recipe.Resources.RecipeDialogStrings", typeof(RecipeDialogStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I have created an appointment on your calendar for 8 PM. That’s all. I will ask your feedback after the party.
        ///Enjoy!.
        /// </summary>
        internal static string APPOINTMENT_CONFIRMATION {
            get {
                return ResourceManager.GetString("APPOINTMENT_CONFIRMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What date are you planning for the dinner?.
        /// </summary>
        internal static string ASK_DINNER_DATE {
            get {
                return ResourceManager.GetString("ASK_DINNER_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What would be the main ingredient?.
        /// </summary>
        internal static string ASK_USER_INPUT_INGREDIENT {
            get {
                return ResourceManager.GetString("ASK_USER_INPUT_INGREDIENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I will update my knowledge base to effectively help you next time.
        ///Meanwhile, I will suggest you a Pizza as a safe choice. May I order it for you?.
        /// </summary>
        internal static string ASK_USER_ORDER_PIZZA {
            get {
                return ResourceManager.GetString("ASK_USER_ORDER_PIZZA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have the following available recipes:.
        /// </summary>
        internal static string AVAILABLE_RECIPES {
            get {
                return ResourceManager.GetString("AVAILABLE_RECIPES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have the following ingredients in your storage:.
        /// </summary>
        internal static string AVAILABLE_STORAGE_INGREDIENTS {
            get {
                return ResourceManager.GetString("AVAILABLE_STORAGE_INGREDIENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}. Is that correct?.
        /// </summary>
        internal static string CONFIRM_DINNER_DATE {
            get {
                return ResourceManager.GetString("CONFIRM_DINNER_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The order is placed and pending confirmation. The purchase amount will be {0}€. You will be using the associated credit card for payment. Do you confirm the order?.
        /// </summary>
        internal static string CONFIRM_TOTAL_PRICE {
            get {
                return ResourceManager.GetString("CONFIRM_TOTAL_PRICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m glad I could help!.
        /// </summary>
        internal static string END_DIALOG {
            get {
                return ResourceManager.GetString("END_DIALOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for your order. You will receive an email with the order details..
        /// </summary>
        internal static string END_PURCHASE {
            get {
                return ResourceManager.GetString("END_PURCHASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have enough ingredients in storage to cook the recipe. Good cooking!.
        /// </summary>
        internal static string ENOUGH_INGREDIENTS {
            get {
                return ResourceManager.GetString("ENOUGH_INGREDIENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take the following ingredients in mind:.
        /// </summary>
        internal static string FOLLOWING_INGREDIENTS {
            get {
                return ResourceManager.GetString("FOLLOWING_INGREDIENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We didn´t find ingredients for that recipe..
        /// </summary>
        internal static string INGREDIENTS_NOT_FOUND {
            get {
                return ResourceManager.GetString("INGREDIENTS_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I can assyst you on the arrangements. Do you need help with the menu?.
        /// </summary>
        internal static string INITIAL_DIALOG {
            get {
                return ResourceManager.GetString("INITIAL_DIALOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Based on your pantry stock, we will need to buy the following ingredients:.
        /// </summary>
        internal static string NECESSARY_INGREDIENTS {
            get {
                return ResourceManager.GetString("NECESSARY_INGREDIENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have available ingredients in storage for this recipe..
        /// </summary>
        internal static string NO_AVAILABLE_STORAGE_INGREDIENTS {
            get {
                return ResourceManager.GetString("NO_AVAILABLE_STORAGE_INGREDIENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How many guest friends would you invite?.
        /// </summary>
        internal static string NUMBER_OF_PEOPLE {
            get {
                return ResourceManager.GetString("NUMBER_OF_PEOPLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let me help you with the meeting request..
        /// </summary>
        internal static string ONLY_MEETING_REQUEST {
            get {
                return ResourceManager.GetString("ONLY_MEETING_REQUEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to May I proceed to the order request?.
        /// </summary>
        internal static string ORDER_NECESSARY_INGREDIENTS {
            get {
                return ResourceManager.GetString("ORDER_NECESSARY_INGREDIENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a.
        /// </summary>
        internal static string ORDER_PIZZA {
            get {
                return ResourceManager.GetString("ORDER_PIZZA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fine! I will now proceed to your UniShop account login..
        /// </summary>
        internal static string PROCEED_LOGIN {
            get {
                return ResourceManager.GetString("PROCEED_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The recipe is not available..
        /// </summary>
        internal static string RECIPE_NOT_AVAILABLE {
            get {
                return ResourceManager.GetString("RECIPE_NOT_AVAILABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you choose the recipe of the week which is {0}, you will get a {1}% discount on {2}. Would it be a good idea?.
        /// </summary>
        internal static string RECIPE_OF_THE_WEEK {
            get {
                return ResourceManager.GetString("RECIPE_OF_THE_WEEK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose a recipe..
        /// </summary>
        internal static string RECIPE_PROMPT {
            get {
                return ResourceManager.GetString("RECIPE_PROMPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Great! I would suggest you the following dishes:.
        /// </summary>
        internal static string RECIPES_SUGESTED {
            get {
                return ResourceManager.GetString("RECIPES_SUGESTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I will update your shopping cart for later use. You can recall it anytime..
        /// </summary>
        internal static string UPDATE_CART_LATER_USE {
            get {
                return ResourceManager.GetString("UPDATE_CART_LATER_USE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to use the ingredients that you have in storage?.
        /// </summary>
        internal static string USE_STORAGE_INGREDIENTS {
            get {
                return ResourceManager.GetString("USE_STORAGE_INGREDIENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which one would you prefer?.
        /// </summary>
        internal static string WHICH_RECIPE_PREFERES {
            get {
                return ResourceManager.GetString("WHICH_RECIPE_PREFERES", resourceCulture);
            }
        }
    }
}
